service: legion-hq-api

package:
  patterns:
    - '!.vscode'
    - '!src/**'
    - '!*.js'
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  users:
    handler: users_app.handler
    name: legion-hq-api-users
    package:
      patterns:
        - "src/users/**"
        - "users_app.js"
  user-lists:
    handler: user_lists_app.handler
    name: legion-hq-api-user-lists
    package:
      patterns:
        - "src/user_lists/**"
        - "user_lists_app.js"